version: '3.9'

volumes:
  postgres-lobo-data:

services:
  lobo-db:
    container_name: lobo-db
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-lobo-data:/var/lib/postgresql/data
    networks:
      - lobo-net
networks:
  lobo-net:
    
      