version: "3.1"

services:
  lobo-liquibase:
    container_name: lobo-liquibase
    image: liquibase/liquibase
    command: update --changelog-file=changelog.xml --username=postgres --password=postgres --url=jdbc:postgresql://lobo-db:5432/postgres
    volumes:
      - ./config/changelog.xml:/liquibase/changelog.xml
      - ./scripts:/liquibase/scripts
    networks:
      - lobo-net
networks:
  lobo-net:    
